### ISSUE TITLE
server exception for gupaoedu-vip-netty-rpc project

### ISSUE THREAD

**Issue by dongluyang** [gupaoedu-tom/netty4-samples#8]
Caused by: java.io.StreamCorruptedException: Unsupported version: 0
	at io.netty.handler.codec.serialization.CompactObjectInputStream.readStreamHeader(CompactObjectInputStream.java:38)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
	at io.netty.handler.codec.serialization.CompactObjectInputStream.<init>(CompactObjectInputStream.java:30)
	at io.netty.handler.codec.serialization.ObjectDecoder.decode(ObjectDecoder.java:74)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 16 more

**Comment by niufwshd** [comment]
@dongluyang ，请问你解决了吗,我也遇到了。

**Comment by niufwshd** [comment]
@dongluyang ，已经解决。把RpcRegistry.java中的第44-46行的注释放开就可以了。
